/**
 * GENERATED FILE. This file was generated by @kayteh/bento. Editing it is a bad idea.
 * @generated
 */
import Bento, { IBentoTransport } from '@kayteh/bento'
export type ServerSlug = {
  id?: string
  name?: string
  ownerID?: string
  icon?: string
}
