// flow-typed signature: bc75aec44ae5fdc84dd56235b22e0cc9
// flow-typed version: <<STUB>>/async-retry_v^1.2.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-retry/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-retry/lib/index.js' {
  declare module.exports: $Exports<'async-retry/lib/index'>;
}
