// flow-typed signature: 8720acc61688402d711803862c45492c
// flow-typed version: <<STUB>>/await-outside_v^2.1.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'await-outside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'await-outside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'await-outside/repl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'await-outside/index' {
  declare module.exports: $Exports<'await-outside'>;
}
declare module 'await-outside/index.js' {
  declare module.exports: $Exports<'await-outside'>;
}
declare module 'await-outside/repl.js' {
  declare module.exports: $Exports<'await-outside/repl'>;
}
