// flow-typed signature: ebcf7353364f219af707d81b3e8caab3
// flow-typed version: <<STUB>>/bufferutil_v^4.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bufferutil'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bufferutil' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bufferutil/fallback' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bufferutil/fallback.js' {
  declare module.exports: $Exports<'bufferutil/fallback'>;
}
declare module 'bufferutil/index' {
  declare module.exports: $Exports<'bufferutil'>;
}
declare module 'bufferutil/index.js' {
  declare module.exports: $Exports<'bufferutil'>;
}
