// flow-typed signature: 432d6a3fa21c7cbfcaf3bc516b214fac
// flow-typed version: <<STUB>>/eris_v^0.9.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eris'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eris' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eris/lib/Client' {
  declare module.exports: any;
}

declare module 'eris/lib/command/Command' {
  declare module.exports: any;
}

declare module 'eris/lib/command/CommandClient' {
  declare module.exports: any;
}

declare module 'eris/lib/Constants' {
  declare module.exports: any;
}

declare module 'eris/lib/errors/DiscordHTTPError' {
  declare module.exports: any;
}

declare module 'eris/lib/errors/DiscordRESTError' {
  declare module.exports: any;
}

declare module 'eris/lib/gateway/Shard' {
  declare module.exports: any;
}

declare module 'eris/lib/gateway/ShardManager' {
  declare module.exports: any;
}

declare module 'eris/lib/rest/Endpoints' {
  declare module.exports: any;
}

declare module 'eris/lib/rest/RequestHandler' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Base' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Call' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/CategoryChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Channel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/ExtendedUser' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/GroupChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Guild' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/GuildAuditLogEntry' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/GuildChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/GuildIntegration' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Invite' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Member' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Message' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Permission' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/PermissionOverwrite' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/PrivateChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Relationship' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/Role' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/TextChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/UnavailableGuild' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/User' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/VoiceChannel' {
  declare module.exports: any;
}

declare module 'eris/lib/structures/VoiceState' {
  declare module.exports: any;
}

declare module 'eris/lib/util/Bucket' {
  declare module.exports: any;
}

declare module 'eris/lib/util/Collection' {
  declare module.exports: any;
}

declare module 'eris/lib/util/MultipartData' {
  declare module.exports: any;
}

declare module 'eris/lib/util/SequentialBucket' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/Piper' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/SharedStream' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/BaseTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/DCAOpusTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/FFmpegDuplex' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/FFmpegOggTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/FFmpegPCMTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/OggOpusTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/PCMOpusTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/VolumeTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/streams/WebmOpusTransformer' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/VoiceConnection' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/VoiceConnectionManager' {
  declare module.exports: any;
}

declare module 'eris/lib/voice/VoiceDataStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eris/index' {
  declare module.exports: $Exports<'eris'>;
}
declare module 'eris/index.js' {
  declare module.exports: $Exports<'eris'>;
}
declare module 'eris/lib/Client.js' {
  declare module.exports: $Exports<'eris/lib/Client'>;
}
declare module 'eris/lib/command/Command.js' {
  declare module.exports: $Exports<'eris/lib/command/Command'>;
}
declare module 'eris/lib/command/CommandClient.js' {
  declare module.exports: $Exports<'eris/lib/command/CommandClient'>;
}
declare module 'eris/lib/Constants.js' {
  declare module.exports: $Exports<'eris/lib/Constants'>;
}
declare module 'eris/lib/errors/DiscordHTTPError.js' {
  declare module.exports: $Exports<'eris/lib/errors/DiscordHTTPError'>;
}
declare module 'eris/lib/errors/DiscordRESTError.js' {
  declare module.exports: $Exports<'eris/lib/errors/DiscordRESTError'>;
}
declare module 'eris/lib/gateway/Shard.js' {
  declare module.exports: $Exports<'eris/lib/gateway/Shard'>;
}
declare module 'eris/lib/gateway/ShardManager.js' {
  declare module.exports: $Exports<'eris/lib/gateway/ShardManager'>;
}
declare module 'eris/lib/rest/Endpoints.js' {
  declare module.exports: $Exports<'eris/lib/rest/Endpoints'>;
}
declare module 'eris/lib/rest/RequestHandler.js' {
  declare module.exports: $Exports<'eris/lib/rest/RequestHandler'>;
}
declare module 'eris/lib/structures/Base.js' {
  declare module.exports: $Exports<'eris/lib/structures/Base'>;
}
declare module 'eris/lib/structures/Call.js' {
  declare module.exports: $Exports<'eris/lib/structures/Call'>;
}
declare module 'eris/lib/structures/CategoryChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/CategoryChannel'>;
}
declare module 'eris/lib/structures/Channel.js' {
  declare module.exports: $Exports<'eris/lib/structures/Channel'>;
}
declare module 'eris/lib/structures/ExtendedUser.js' {
  declare module.exports: $Exports<'eris/lib/structures/ExtendedUser'>;
}
declare module 'eris/lib/structures/GroupChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/GroupChannel'>;
}
declare module 'eris/lib/structures/Guild.js' {
  declare module.exports: $Exports<'eris/lib/structures/Guild'>;
}
declare module 'eris/lib/structures/GuildAuditLogEntry.js' {
  declare module.exports: $Exports<'eris/lib/structures/GuildAuditLogEntry'>;
}
declare module 'eris/lib/structures/GuildChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/GuildChannel'>;
}
declare module 'eris/lib/structures/GuildIntegration.js' {
  declare module.exports: $Exports<'eris/lib/structures/GuildIntegration'>;
}
declare module 'eris/lib/structures/Invite.js' {
  declare module.exports: $Exports<'eris/lib/structures/Invite'>;
}
declare module 'eris/lib/structures/Member.js' {
  declare module.exports: $Exports<'eris/lib/structures/Member'>;
}
declare module 'eris/lib/structures/Message.js' {
  declare module.exports: $Exports<'eris/lib/structures/Message'>;
}
declare module 'eris/lib/structures/Permission.js' {
  declare module.exports: $Exports<'eris/lib/structures/Permission'>;
}
declare module 'eris/lib/structures/PermissionOverwrite.js' {
  declare module.exports: $Exports<'eris/lib/structures/PermissionOverwrite'>;
}
declare module 'eris/lib/structures/PrivateChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/PrivateChannel'>;
}
declare module 'eris/lib/structures/Relationship.js' {
  declare module.exports: $Exports<'eris/lib/structures/Relationship'>;
}
declare module 'eris/lib/structures/Role.js' {
  declare module.exports: $Exports<'eris/lib/structures/Role'>;
}
declare module 'eris/lib/structures/TextChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/TextChannel'>;
}
declare module 'eris/lib/structures/UnavailableGuild.js' {
  declare module.exports: $Exports<'eris/lib/structures/UnavailableGuild'>;
}
declare module 'eris/lib/structures/User.js' {
  declare module.exports: $Exports<'eris/lib/structures/User'>;
}
declare module 'eris/lib/structures/VoiceChannel.js' {
  declare module.exports: $Exports<'eris/lib/structures/VoiceChannel'>;
}
declare module 'eris/lib/structures/VoiceState.js' {
  declare module.exports: $Exports<'eris/lib/structures/VoiceState'>;
}
declare module 'eris/lib/util/Bucket.js' {
  declare module.exports: $Exports<'eris/lib/util/Bucket'>;
}
declare module 'eris/lib/util/Collection.js' {
  declare module.exports: $Exports<'eris/lib/util/Collection'>;
}
declare module 'eris/lib/util/MultipartData.js' {
  declare module.exports: $Exports<'eris/lib/util/MultipartData'>;
}
declare module 'eris/lib/util/SequentialBucket.js' {
  declare module.exports: $Exports<'eris/lib/util/SequentialBucket'>;
}
declare module 'eris/lib/voice/Piper.js' {
  declare module.exports: $Exports<'eris/lib/voice/Piper'>;
}
declare module 'eris/lib/voice/SharedStream.js' {
  declare module.exports: $Exports<'eris/lib/voice/SharedStream'>;
}
declare module 'eris/lib/voice/streams/BaseTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/BaseTransformer'>;
}
declare module 'eris/lib/voice/streams/DCAOpusTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/DCAOpusTransformer'>;
}
declare module 'eris/lib/voice/streams/FFmpegDuplex.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/FFmpegDuplex'>;
}
declare module 'eris/lib/voice/streams/FFmpegOggTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/FFmpegOggTransformer'>;
}
declare module 'eris/lib/voice/streams/FFmpegPCMTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/FFmpegPCMTransformer'>;
}
declare module 'eris/lib/voice/streams/OggOpusTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/OggOpusTransformer'>;
}
declare module 'eris/lib/voice/streams/PCMOpusTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/PCMOpusTransformer'>;
}
declare module 'eris/lib/voice/streams/VolumeTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/VolumeTransformer'>;
}
declare module 'eris/lib/voice/streams/WebmOpusTransformer.js' {
  declare module.exports: $Exports<'eris/lib/voice/streams/WebmOpusTransformer'>;
}
declare module 'eris/lib/voice/VoiceConnection.js' {
  declare module.exports: $Exports<'eris/lib/voice/VoiceConnection'>;
}
declare module 'eris/lib/voice/VoiceConnectionManager.js' {
  declare module.exports: $Exports<'eris/lib/voice/VoiceConnectionManager'>;
}
declare module 'eris/lib/voice/VoiceDataStream.js' {
  declare module.exports: $Exports<'eris/lib/voice/VoiceDataStream'>;
}
