// flow-typed signature: e71faa0399b5509e750da57d6468739b
// flow-typed version: <<STUB>>/erlpack_vhammerandchisel/erlpack/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'erlpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'erlpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'erlpack/js/__tests__/decoder-test' {
  declare module.exports: any;
}

declare module 'erlpack/js/__tests__/encoder-test' {
  declare module.exports: any;
}

declare module 'erlpack/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'erlpack/js/__tests__/decoder-test.js' {
  declare module.exports: $Exports<'erlpack/js/__tests__/decoder-test'>;
}
declare module 'erlpack/js/__tests__/encoder-test.js' {
  declare module.exports: $Exports<'erlpack/js/__tests__/encoder-test'>;
}
declare module 'erlpack/js/index.js' {
  declare module.exports: $Exports<'erlpack/js/index'>;
}
