// flow-typed signature: e8145f7f4fa94963b20c369e3e852cb5
// flow-typed version: <<STUB>>/fast-redux_v^0.7.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-redux/dist/fast-redux' {
  declare module.exports: any;
}

declare module 'fast-redux/dist/fast-redux.min' {
  declare module.exports: any;
}

declare module 'fast-redux/es/index' {
  declare module.exports: any;
}

declare module 'fast-redux/es/namespace' {
  declare module.exports: any;
}

declare module 'fast-redux/es/object' {
  declare module.exports: any;
}

declare module 'fast-redux/es/rootReducer' {
  declare module.exports: any;
}

declare module 'fast-redux/lib/index' {
  declare module.exports: any;
}

declare module 'fast-redux/lib/namespace' {
  declare module.exports: any;
}

declare module 'fast-redux/lib/object' {
  declare module.exports: any;
}

declare module 'fast-redux/lib/rootReducer' {
  declare module.exports: any;
}

declare module 'fast-redux/src/index' {
  declare module.exports: any;
}

declare module 'fast-redux/src/namespace' {
  declare module.exports: any;
}

declare module 'fast-redux/src/object' {
  declare module.exports: any;
}

declare module 'fast-redux/src/rootReducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-redux/dist/fast-redux.js' {
  declare module.exports: $Exports<'fast-redux/dist/fast-redux'>;
}
declare module 'fast-redux/dist/fast-redux.min.js' {
  declare module.exports: $Exports<'fast-redux/dist/fast-redux.min'>;
}
declare module 'fast-redux/es/index.js' {
  declare module.exports: $Exports<'fast-redux/es/index'>;
}
declare module 'fast-redux/es/namespace.js' {
  declare module.exports: $Exports<'fast-redux/es/namespace'>;
}
declare module 'fast-redux/es/object.js' {
  declare module.exports: $Exports<'fast-redux/es/object'>;
}
declare module 'fast-redux/es/rootReducer.js' {
  declare module.exports: $Exports<'fast-redux/es/rootReducer'>;
}
declare module 'fast-redux/lib/index.js' {
  declare module.exports: $Exports<'fast-redux/lib/index'>;
}
declare module 'fast-redux/lib/namespace.js' {
  declare module.exports: $Exports<'fast-redux/lib/namespace'>;
}
declare module 'fast-redux/lib/object.js' {
  declare module.exports: $Exports<'fast-redux/lib/object'>;
}
declare module 'fast-redux/lib/rootReducer.js' {
  declare module.exports: $Exports<'fast-redux/lib/rootReducer'>;
}
declare module 'fast-redux/src/index.js' {
  declare module.exports: $Exports<'fast-redux/src/index'>;
}
declare module 'fast-redux/src/namespace.js' {
  declare module.exports: $Exports<'fast-redux/src/namespace'>;
}
declare module 'fast-redux/src/object.js' {
  declare module.exports: $Exports<'fast-redux/src/object'>;
}
declare module 'fast-redux/src/rootReducer.js' {
  declare module.exports: $Exports<'fast-redux/src/rootReducer'>;
}
