// flow-typed signature: 238a686d4f6643cbcb06749cdc91081f
// flow-typed version: <<STUB>>/keygrip_v^1.0.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keygrip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keygrip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'keygrip/index' {
  declare module.exports: $Exports<'keygrip'>;
}
declare module 'keygrip/index.js' {
  declare module.exports: $Exports<'keygrip'>;
}
