// flow-typed signature: f1d1f28d3404d28e0b3a544b1db1f1e5
// flow-typed version: <<STUB>>/kompression_v^1.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kompression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kompression' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kompression/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kompression/src/index.js' {
  declare module.exports: $Exports<'kompression/src/index'>;
}
