// flow-typed signature: fc54320c7e65ac8dd6dd59d867d850af
// flow-typed version: <<STUB>>/ksuid_v^1.1.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ksuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ksuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ksuid/base62' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ksuid/base62.js' {
  declare module.exports: $Exports<'ksuid/base62'>;
}
declare module 'ksuid/index' {
  declare module.exports: $Exports<'ksuid'>;
}
declare module 'ksuid/index.js' {
  declare module.exports: $Exports<'ksuid'>;
}
