// flow-typed signature: c88b73e7590eadbdffc19aedb4e392c0
// flow-typed version: <<STUB>>/moniker_v^0.1.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moniker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moniker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moniker/examples/moniker' {
  declare module.exports: any;
}

declare module 'moniker/lib/moniker' {
  declare module.exports: any;
}

declare module 'moniker/test/moniker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moniker/examples/moniker.js' {
  declare module.exports: $Exports<'moniker/examples/moniker'>;
}
declare module 'moniker/lib/moniker.js' {
  declare module.exports: $Exports<'moniker/lib/moniker'>;
}
declare module 'moniker/test/moniker.js' {
  declare module.exports: $Exports<'moniker/test/moniker'>;
}
