// flow-typed signature: 992c245c5628a3bc1775f9c8b188d229
// flow-typed version: <<STUB>>/nanoid_v^2.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanoid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanoid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanoid/async/format' {
  declare module.exports: any;
}

declare module 'nanoid/async/generate' {
  declare module.exports: any;
}

declare module 'nanoid/async/index.browser' {
  declare module.exports: any;
}

declare module 'nanoid/async/index' {
  declare module.exports: any;
}

declare module 'nanoid/async/random.browser' {
  declare module.exports: any;
}

declare module 'nanoid/async/random' {
  declare module.exports: any;
}

declare module 'nanoid/format' {
  declare module.exports: any;
}

declare module 'nanoid/generate' {
  declare module.exports: any;
}

declare module 'nanoid/index.browser' {
  declare module.exports: any;
}

declare module 'nanoid/non-secure/generate' {
  declare module.exports: any;
}

declare module 'nanoid/non-secure/index' {
  declare module.exports: any;
}

declare module 'nanoid/random.browser' {
  declare module.exports: any;
}

declare module 'nanoid/random' {
  declare module.exports: any;
}

declare module 'nanoid/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanoid/async/format.js' {
  declare module.exports: $Exports<'nanoid/async/format'>;
}
declare module 'nanoid/async/generate.js' {
  declare module.exports: $Exports<'nanoid/async/generate'>;
}
declare module 'nanoid/async/index.browser.js' {
  declare module.exports: $Exports<'nanoid/async/index.browser'>;
}
declare module 'nanoid/async/index.js' {
  declare module.exports: $Exports<'nanoid/async/index'>;
}
declare module 'nanoid/async/random.browser.js' {
  declare module.exports: $Exports<'nanoid/async/random.browser'>;
}
declare module 'nanoid/async/random.js' {
  declare module.exports: $Exports<'nanoid/async/random'>;
}
declare module 'nanoid/format.js' {
  declare module.exports: $Exports<'nanoid/format'>;
}
declare module 'nanoid/generate.js' {
  declare module.exports: $Exports<'nanoid/generate'>;
}
declare module 'nanoid/index.browser.js' {
  declare module.exports: $Exports<'nanoid/index.browser'>;
}
declare module 'nanoid/index' {
  declare module.exports: $Exports<'nanoid'>;
}
declare module 'nanoid/index.js' {
  declare module.exports: $Exports<'nanoid'>;
}
declare module 'nanoid/non-secure/generate.js' {
  declare module.exports: $Exports<'nanoid/non-secure/generate'>;
}
declare module 'nanoid/non-secure/index.js' {
  declare module.exports: $Exports<'nanoid/non-secure/index'>;
}
declare module 'nanoid/random.browser.js' {
  declare module.exports: $Exports<'nanoid/random.browser'>;
}
declare module 'nanoid/random.js' {
  declare module.exports: $Exports<'nanoid/random'>;
}
declare module 'nanoid/url.js' {
  declare module.exports: $Exports<'nanoid/url'>;
}
