// flow-typed signature: 2a12daa51dbc8fa4b2bea9c494c4b71e
// flow-typed version: <<STUB>>/next-redux-wrapper_v^3.0.0-alpha.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-wrapper/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/es6/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/es6/index.spec' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/lib/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/lib/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-wrapper/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'next-redux-wrapper/coverage/lcov-report/block-navigation'>;
}
declare module 'next-redux-wrapper/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'next-redux-wrapper/coverage/lcov-report/prettify'>;
}
declare module 'next-redux-wrapper/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'next-redux-wrapper/coverage/lcov-report/sorter'>;
}
declare module 'next-redux-wrapper/es6/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/es6/index'>;
}
declare module 'next-redux-wrapper/es6/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/es6/index.spec'>;
}
declare module 'next-redux-wrapper/lib/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/lib/index'>;
}
declare module 'next-redux-wrapper/lib/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/lib/index.spec'>;
}
