// flow-typed signature: 41176daaece69384f78eaf010c9437d4
// flow-typed version: <<STUB>>/pm2_v^3.3.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pm2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pm2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pm2/constants' {
  declare module.exports: any;
}

declare module 'pm2/lib/API' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/CliUx' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Configuration' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Containerizer' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Dashboard' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Deploy' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Extra' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Log' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/LogManagement' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/flagExt' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/flagWatch' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/HTTP' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/index' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/LOCAL' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/Modularizer' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/NPM' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Modules/TAR' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Monit' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/auth-strategies/CliAuth' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/auth-strategies/WebAuth' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/helpers' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/link' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/PM2IO' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/pm2-plus/process-selector' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Serve' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Spinner' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Startup' {
  declare module.exports: any;
}

declare module 'pm2/lib/API/Version' {
  declare module.exports: any;
}

declare module 'pm2/lib/binaries/DevCLI' {
  declare module.exports: any;
}

declare module 'pm2/lib/binaries/Runtime' {
  declare module.exports: any;
}

declare module 'pm2/lib/binaries/Runtime4Docker' {
  declare module.exports: any;
}

declare module 'pm2/lib/Client' {
  declare module.exports: any;
}

declare module 'pm2/lib/Common' {
  declare module.exports: any;
}

declare module 'pm2/lib/completion' {
  declare module.exports: any;
}

declare module 'pm2/lib/Configuration' {
  declare module.exports: any;
}

declare module 'pm2/lib/Daemon' {
  declare module.exports: any;
}

declare module 'pm2/lib/Event' {
  declare module.exports: any;
}

declare module 'pm2/lib/God' {
  declare module.exports: any;
}

declare module 'pm2/lib/God/ActionMethods' {
  declare module.exports: any;
}

declare module 'pm2/lib/God/ClusterMode' {
  declare module.exports: any;
}

declare module 'pm2/lib/God/ForkMode' {
  declare module.exports: any;
}

declare module 'pm2/lib/God/Methods' {
  declare module.exports: any;
}

declare module 'pm2/lib/God/Reload' {
  declare module.exports: any;
}

declare module 'pm2/lib/HttpInterface' {
  declare module.exports: any;
}

declare module 'pm2/lib/ProcessContainer' {
  declare module.exports: any;
}

declare module 'pm2/lib/ProcessContainerFork' {
  declare module.exports: any;
}

declare module 'pm2/lib/ProcessUtils' {
  declare module.exports: any;
}

declare module 'pm2/lib/Satan' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/Config' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/find-package-json' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/fmt' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/IsAbsolute' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/isbinaryfile' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/json5' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/open' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/passwd' {
  declare module.exports: any;
}

declare module 'pm2/lib/tools/promise.min' {
  declare module.exports: any;
}

declare module 'pm2/lib/TreeKill' {
  declare module.exports: any;
}

declare module 'pm2/lib/Utility' {
  declare module.exports: any;
}

declare module 'pm2/lib/Watcher' {
  declare module.exports: any;
}

declare module 'pm2/lib/Worker' {
  declare module.exports: any;
}

declare module 'pm2/paths' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pm2/constants.js' {
  declare module.exports: $Exports<'pm2/constants'>;
}
declare module 'pm2/index' {
  declare module.exports: $Exports<'pm2'>;
}
declare module 'pm2/index.js' {
  declare module.exports: $Exports<'pm2'>;
}
declare module 'pm2/lib/API.js' {
  declare module.exports: $Exports<'pm2/lib/API'>;
}
declare module 'pm2/lib/API/CliUx.js' {
  declare module.exports: $Exports<'pm2/lib/API/CliUx'>;
}
declare module 'pm2/lib/API/Configuration.js' {
  declare module.exports: $Exports<'pm2/lib/API/Configuration'>;
}
declare module 'pm2/lib/API/Containerizer.js' {
  declare module.exports: $Exports<'pm2/lib/API/Containerizer'>;
}
declare module 'pm2/lib/API/Dashboard.js' {
  declare module.exports: $Exports<'pm2/lib/API/Dashboard'>;
}
declare module 'pm2/lib/API/Deploy.js' {
  declare module.exports: $Exports<'pm2/lib/API/Deploy'>;
}
declare module 'pm2/lib/API/Extra.js' {
  declare module.exports: $Exports<'pm2/lib/API/Extra'>;
}
declare module 'pm2/lib/API/Log.js' {
  declare module.exports: $Exports<'pm2/lib/API/Log'>;
}
declare module 'pm2/lib/API/LogManagement.js' {
  declare module.exports: $Exports<'pm2/lib/API/LogManagement'>;
}
declare module 'pm2/lib/API/Modules/flagExt.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/flagExt'>;
}
declare module 'pm2/lib/API/Modules/flagWatch.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/flagWatch'>;
}
declare module 'pm2/lib/API/Modules/HTTP.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/HTTP'>;
}
declare module 'pm2/lib/API/Modules/index.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/index'>;
}
declare module 'pm2/lib/API/Modules/LOCAL.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/LOCAL'>;
}
declare module 'pm2/lib/API/Modules/Modularizer.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/Modularizer'>;
}
declare module 'pm2/lib/API/Modules/NPM.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/NPM'>;
}
declare module 'pm2/lib/API/Modules/TAR.js' {
  declare module.exports: $Exports<'pm2/lib/API/Modules/TAR'>;
}
declare module 'pm2/lib/API/Monit.js' {
  declare module.exports: $Exports<'pm2/lib/API/Monit'>;
}
declare module 'pm2/lib/API/pm2-plus/auth-strategies/CliAuth.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/auth-strategies/CliAuth'>;
}
declare module 'pm2/lib/API/pm2-plus/auth-strategies/WebAuth.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/auth-strategies/WebAuth'>;
}
declare module 'pm2/lib/API/pm2-plus/helpers.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/helpers'>;
}
declare module 'pm2/lib/API/pm2-plus/link.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/link'>;
}
declare module 'pm2/lib/API/pm2-plus/PM2IO.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/PM2IO'>;
}
declare module 'pm2/lib/API/pm2-plus/process-selector.js' {
  declare module.exports: $Exports<'pm2/lib/API/pm2-plus/process-selector'>;
}
declare module 'pm2/lib/API/Serve.js' {
  declare module.exports: $Exports<'pm2/lib/API/Serve'>;
}
declare module 'pm2/lib/API/Spinner.js' {
  declare module.exports: $Exports<'pm2/lib/API/Spinner'>;
}
declare module 'pm2/lib/API/Startup.js' {
  declare module.exports: $Exports<'pm2/lib/API/Startup'>;
}
declare module 'pm2/lib/API/Version.js' {
  declare module.exports: $Exports<'pm2/lib/API/Version'>;
}
declare module 'pm2/lib/binaries/DevCLI.js' {
  declare module.exports: $Exports<'pm2/lib/binaries/DevCLI'>;
}
declare module 'pm2/lib/binaries/Runtime.js' {
  declare module.exports: $Exports<'pm2/lib/binaries/Runtime'>;
}
declare module 'pm2/lib/binaries/Runtime4Docker.js' {
  declare module.exports: $Exports<'pm2/lib/binaries/Runtime4Docker'>;
}
declare module 'pm2/lib/Client.js' {
  declare module.exports: $Exports<'pm2/lib/Client'>;
}
declare module 'pm2/lib/Common.js' {
  declare module.exports: $Exports<'pm2/lib/Common'>;
}
declare module 'pm2/lib/completion.js' {
  declare module.exports: $Exports<'pm2/lib/completion'>;
}
declare module 'pm2/lib/Configuration.js' {
  declare module.exports: $Exports<'pm2/lib/Configuration'>;
}
declare module 'pm2/lib/Daemon.js' {
  declare module.exports: $Exports<'pm2/lib/Daemon'>;
}
declare module 'pm2/lib/Event.js' {
  declare module.exports: $Exports<'pm2/lib/Event'>;
}
declare module 'pm2/lib/God.js' {
  declare module.exports: $Exports<'pm2/lib/God'>;
}
declare module 'pm2/lib/God/ActionMethods.js' {
  declare module.exports: $Exports<'pm2/lib/God/ActionMethods'>;
}
declare module 'pm2/lib/God/ClusterMode.js' {
  declare module.exports: $Exports<'pm2/lib/God/ClusterMode'>;
}
declare module 'pm2/lib/God/ForkMode.js' {
  declare module.exports: $Exports<'pm2/lib/God/ForkMode'>;
}
declare module 'pm2/lib/God/Methods.js' {
  declare module.exports: $Exports<'pm2/lib/God/Methods'>;
}
declare module 'pm2/lib/God/Reload.js' {
  declare module.exports: $Exports<'pm2/lib/God/Reload'>;
}
declare module 'pm2/lib/HttpInterface.js' {
  declare module.exports: $Exports<'pm2/lib/HttpInterface'>;
}
declare module 'pm2/lib/ProcessContainer.js' {
  declare module.exports: $Exports<'pm2/lib/ProcessContainer'>;
}
declare module 'pm2/lib/ProcessContainerFork.js' {
  declare module.exports: $Exports<'pm2/lib/ProcessContainerFork'>;
}
declare module 'pm2/lib/ProcessUtils.js' {
  declare module.exports: $Exports<'pm2/lib/ProcessUtils'>;
}
declare module 'pm2/lib/Satan.js' {
  declare module.exports: $Exports<'pm2/lib/Satan'>;
}
declare module 'pm2/lib/tools/Config.js' {
  declare module.exports: $Exports<'pm2/lib/tools/Config'>;
}
declare module 'pm2/lib/tools/find-package-json.js' {
  declare module.exports: $Exports<'pm2/lib/tools/find-package-json'>;
}
declare module 'pm2/lib/tools/fmt.js' {
  declare module.exports: $Exports<'pm2/lib/tools/fmt'>;
}
declare module 'pm2/lib/tools/IsAbsolute.js' {
  declare module.exports: $Exports<'pm2/lib/tools/IsAbsolute'>;
}
declare module 'pm2/lib/tools/isbinaryfile.js' {
  declare module.exports: $Exports<'pm2/lib/tools/isbinaryfile'>;
}
declare module 'pm2/lib/tools/json5.js' {
  declare module.exports: $Exports<'pm2/lib/tools/json5'>;
}
declare module 'pm2/lib/tools/open.js' {
  declare module.exports: $Exports<'pm2/lib/tools/open'>;
}
declare module 'pm2/lib/tools/passwd.js' {
  declare module.exports: $Exports<'pm2/lib/tools/passwd'>;
}
declare module 'pm2/lib/tools/promise.min.js' {
  declare module.exports: $Exports<'pm2/lib/tools/promise.min'>;
}
declare module 'pm2/lib/TreeKill.js' {
  declare module.exports: $Exports<'pm2/lib/TreeKill'>;
}
declare module 'pm2/lib/Utility.js' {
  declare module.exports: $Exports<'pm2/lib/Utility'>;
}
declare module 'pm2/lib/Watcher.js' {
  declare module.exports: $Exports<'pm2/lib/Watcher'>;
}
declare module 'pm2/lib/Worker.js' {
  declare module.exports: $Exports<'pm2/lib/Worker'>;
}
declare module 'pm2/paths.js' {
  declare module.exports: $Exports<'pm2/paths'>;
}
