// flow-typed signature: 0a3f15218c03e4d21b1bef8608378645
// flow-typed version: <<STUB>>/primer_v^11.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primer/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primer/build/index.js' {
  declare module.exports: $Exports<'primer/build/index'>;
}
