// flow-typed signature: c53c9fc70f7372ce9e832b9ea8a26abc
// flow-typed version: <<STUB>>/react-typist_v^2.0.5/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-typist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-typist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-typist/dist/standalone/Typist' {
  declare module.exports: any;
}

declare module 'react-typist/dist/standalone/Typist.min' {
  declare module.exports: any;
}

declare module 'react-typist/dist/Typist' {
  declare module.exports: any;
}

declare module 'react-typist/src/Backspace' {
  declare module.exports: any;
}

declare module 'react-typist/src/Cursor' {
  declare module.exports: any;
}

declare module 'react-typist/src/Delay' {
  declare module.exports: any;
}

declare module 'react-typist/src/Typist' {
  declare module.exports: any;
}

declare module 'react-typist/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-typist/dist/standalone/Typist.js' {
  declare module.exports: $Exports<'react-typist/dist/standalone/Typist'>;
}
declare module 'react-typist/dist/standalone/Typist.min.js' {
  declare module.exports: $Exports<'react-typist/dist/standalone/Typist.min'>;
}
declare module 'react-typist/dist/Typist.js' {
  declare module.exports: $Exports<'react-typist/dist/Typist'>;
}
declare module 'react-typist/src/Backspace.jsx' {
  declare module.exports: $Exports<'react-typist/src/Backspace'>;
}
declare module 'react-typist/src/Cursor.jsx' {
  declare module.exports: $Exports<'react-typist/src/Cursor'>;
}
declare module 'react-typist/src/Delay.jsx' {
  declare module.exports: $Exports<'react-typist/src/Delay'>;
}
declare module 'react-typist/src/Typist.jsx' {
  declare module.exports: $Exports<'react-typist/src/Typist'>;
}
declare module 'react-typist/src/utils.js' {
  declare module.exports: $Exports<'react-typist/src/utils'>;
}
