// flow-typed signature: ea32702e42500ea2f15fd4c3b3c503a5
// flow-typed version: <<STUB>>/zlib-sync_v^0.1.4/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zlib-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zlib-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'zlib-sync/index' {
  declare module.exports: $Exports<'zlib-sync'>;
}
declare module 'zlib-sync/index.js' {
  declare module.exports: $Exports<'zlib-sync'>;
}
