/**
 * GENERATED FILE. This file was generated by @kayteh/bento. Editing it is a bad idea.
 * @generated
 */
import Bento, { IBentoTransport } from '@kayteh/bento'
export type HelloMsg = {
  hello?: string
}

export type HelloReply = {
  message?: string
}

export interface IMockBotService {
  helloBot (ctx: any, request: HelloMsg): Promise<HelloReply> | HelloReply
}
export class MockBotClient {
  static __SERVICE__: string = 'MockBot'
  constructor (private bento: Bento, private transport?: IBentoTransport) {}
  async helloBot (request: HelloMsg): Promise<HelloReply> {
    return this.bento.makeRequest(this.transport || undefined, 'MockBot', 'HelloBot', request)
  }
}

export interface IMockBackendService {
  helloBackend (ctx: any, request: HelloMsg): Promise<HelloReply> | HelloReply
}
export class MockBackendClient {
  static __SERVICE__: string = 'MockBackend'
  constructor (private bento: Bento, private transport?: IBentoTransport) {}
  async helloBackend (request: HelloMsg): Promise<HelloReply> {
    return this.bento.makeRequest(this.transport || undefined, 'MockBackend', 'HelloBackend', request)
  }
}
