// flow-typed signature: fc5d257a33526e413374777a0ca3fa56
// flow-typed version: <<STUB>>/@discordjs/uws_v^11.149.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@discordjs/uws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@discordjs/uws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@discordjs/uws/uws' {
  declare module.exports: any;
}

// Filename aliases
declare module '@discordjs/uws/uws.js' {
  declare module.exports: $Exports<'@discordjs/uws/uws'>;
}
