// flow-typed signature: 96e25376ad0cc98347e01eae00fc9561
// flow-typed version: <<STUB>>/@roleypoly/ui_v^2.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@roleypoly/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@roleypoly/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@roleypoly/ui/components/__test__/discord-button.test' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/__test__/discord-guild-pic.test' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/demos/tap' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/demos/typing' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/discord-button' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/discord-guild-pic' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/global-colors' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/header/auth' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/header/common' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/header/unauth' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/layout' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/logo' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/role/__test__/demo.test' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/role/__test__/Role.test' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/role/demo' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/role/index' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/role/role.styled' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/social-cards' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/components/tooltip' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/config/demo' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/config/redux' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/config/rpc' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/connector' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/containers/header-bar' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/kit/__test__/media.test' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/kit/debug-breakpoints' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/kit/media' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/lib/redirect' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/next.config' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_app' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_document' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_error' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_internal/_discordbot/_auth' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_internal/_discordbot/_magic' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_internal/_server_add' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_internal/_server' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_test/error' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/_test/landing-mock' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/auth/expired' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/auth/login' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/help/why-no-roles' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/index' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/pages/testrpc' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/rpc/index' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/setupTests' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/stores/currentServer' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/stores/roles' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/stores/servers' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/stores/user' {
  declare module.exports: any;
}

declare module '@roleypoly/ui/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@roleypoly/ui/components/__test__/discord-button.test.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/__test__/discord-button.test'>;
}
declare module '@roleypoly/ui/components/__test__/discord-guild-pic.test.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/__test__/discord-guild-pic.test'>;
}
declare module '@roleypoly/ui/components/demos/tap.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/demos/tap'>;
}
declare module '@roleypoly/ui/components/demos/typing.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/demos/typing'>;
}
declare module '@roleypoly/ui/components/discord-button.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/discord-button'>;
}
declare module '@roleypoly/ui/components/discord-guild-pic.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/discord-guild-pic'>;
}
declare module '@roleypoly/ui/components/global-colors.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/global-colors'>;
}
declare module '@roleypoly/ui/components/header/auth.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/header/auth'>;
}
declare module '@roleypoly/ui/components/header/common.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/header/common'>;
}
declare module '@roleypoly/ui/components/header/unauth.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/header/unauth'>;
}
declare module '@roleypoly/ui/components/layout.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/layout'>;
}
declare module '@roleypoly/ui/components/logo.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/logo'>;
}
declare module '@roleypoly/ui/components/role/__test__/demo.test.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/role/__test__/demo.test'>;
}
declare module '@roleypoly/ui/components/role/__test__/Role.test.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/role/__test__/Role.test'>;
}
declare module '@roleypoly/ui/components/role/demo.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/role/demo'>;
}
declare module '@roleypoly/ui/components/role/index.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/role/index'>;
}
declare module '@roleypoly/ui/components/role/role.styled.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/role/role.styled'>;
}
declare module '@roleypoly/ui/components/social-cards.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/social-cards'>;
}
declare module '@roleypoly/ui/components/tooltip.js' {
  declare module.exports: $Exports<'@roleypoly/ui/components/tooltip'>;
}
declare module '@roleypoly/ui/config/demo.js' {
  declare module.exports: $Exports<'@roleypoly/ui/config/demo'>;
}
declare module '@roleypoly/ui/config/redux.js' {
  declare module.exports: $Exports<'@roleypoly/ui/config/redux'>;
}
declare module '@roleypoly/ui/config/rpc.js' {
  declare module.exports: $Exports<'@roleypoly/ui/config/rpc'>;
}
declare module '@roleypoly/ui/connector.js' {
  declare module.exports: $Exports<'@roleypoly/ui/connector'>;
}
declare module '@roleypoly/ui/containers/header-bar.js' {
  declare module.exports: $Exports<'@roleypoly/ui/containers/header-bar'>;
}
declare module '@roleypoly/ui/kit/__test__/media.test.js' {
  declare module.exports: $Exports<'@roleypoly/ui/kit/__test__/media.test'>;
}
declare module '@roleypoly/ui/kit/debug-breakpoints.js' {
  declare module.exports: $Exports<'@roleypoly/ui/kit/debug-breakpoints'>;
}
declare module '@roleypoly/ui/kit/media.js' {
  declare module.exports: $Exports<'@roleypoly/ui/kit/media'>;
}
declare module '@roleypoly/ui/lib/redirect.js' {
  declare module.exports: $Exports<'@roleypoly/ui/lib/redirect'>;
}
declare module '@roleypoly/ui/next.config.js' {
  declare module.exports: $Exports<'@roleypoly/ui/next.config'>;
}
declare module '@roleypoly/ui/pages/_app.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_app'>;
}
declare module '@roleypoly/ui/pages/_document.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_document'>;
}
declare module '@roleypoly/ui/pages/_error.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_error'>;
}
declare module '@roleypoly/ui/pages/_internal/_discordbot/_auth.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_internal/_discordbot/_auth'>;
}
declare module '@roleypoly/ui/pages/_internal/_discordbot/_magic.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_internal/_discordbot/_magic'>;
}
declare module '@roleypoly/ui/pages/_internal/_server_add.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_internal/_server_add'>;
}
declare module '@roleypoly/ui/pages/_internal/_server.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_internal/_server'>;
}
declare module '@roleypoly/ui/pages/_test/error.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_test/error'>;
}
declare module '@roleypoly/ui/pages/_test/landing-mock.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/_test/landing-mock'>;
}
declare module '@roleypoly/ui/pages/auth/expired.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/auth/expired'>;
}
declare module '@roleypoly/ui/pages/auth/login.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/auth/login'>;
}
declare module '@roleypoly/ui/pages/help/why-no-roles.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/help/why-no-roles'>;
}
declare module '@roleypoly/ui/pages/index.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/index'>;
}
declare module '@roleypoly/ui/pages/testrpc.js' {
  declare module.exports: $Exports<'@roleypoly/ui/pages/testrpc'>;
}
declare module '@roleypoly/ui/rpc/index.js' {
  declare module.exports: $Exports<'@roleypoly/ui/rpc/index'>;
}
declare module '@roleypoly/ui/setupTests.js' {
  declare module.exports: $Exports<'@roleypoly/ui/setupTests'>;
}
declare module '@roleypoly/ui/stores/currentServer.js' {
  declare module.exports: $Exports<'@roleypoly/ui/stores/currentServer'>;
}
declare module '@roleypoly/ui/stores/roles.js' {
  declare module.exports: $Exports<'@roleypoly/ui/stores/roles'>;
}
declare module '@roleypoly/ui/stores/servers.js' {
  declare module.exports: $Exports<'@roleypoly/ui/stores/servers'>;
}
declare module '@roleypoly/ui/stores/user.js' {
  declare module.exports: $Exports<'@roleypoly/ui/stores/user'>;
}
declare module '@roleypoly/ui/types.js' {
  declare module.exports: $Exports<'@roleypoly/ui/types'>;
}
