// flow-typed signature: 79c7c0ba71f3008918485db388c0023b
// flow-typed version: <<STUB>>/@primer/components_v^11.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@primer/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@primer/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@primer/components/codemods/__tests__/v1' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/__tests__/v2' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/__tests__/v3' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/__tests__/v4' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/lib/modifyProps' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/lib/prettify' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/lib/renameImports' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/lib/replaceImportSource' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/v1' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/v2' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/v3' {
  declare module.exports: any;
}

declare module '@primer/components/codemods/v4' {
  declare module.exports: any;
}

declare module '@primer/components/css' {
  declare module.exports: any;
}

declare module '@primer/components/dist/css' {
  declare module.exports: any;
}

declare module '@primer/components/dist/index.esm' {
  declare module.exports: any;
}

declare module '@primer/components/dist/index.umd' {
  declare module.exports: any;
}

declare module '@primer/components/src/Avatar' {
  declare module.exports: any;
}

declare module '@primer/components/src/AvatarPair' {
  declare module.exports: any;
}

declare module '@primer/components/src/BaseStyles' {
  declare module.exports: any;
}

declare module '@primer/components/src/BorderBox' {
  declare module.exports: any;
}

declare module '@primer/components/src/Box' {
  declare module.exports: any;
}

declare module '@primer/components/src/BranchName' {
  declare module.exports: any;
}

declare module '@primer/components/src/Button' {
  declare module.exports: any;
}

declare module '@primer/components/src/ButtonDanger' {
  declare module.exports: any;
}

declare module '@primer/components/src/ButtonOutline' {
  declare module.exports: any;
}

declare module '@primer/components/src/ButtonPrimary' {
  declare module.exports: any;
}

declare module '@primer/components/src/ButtonStyles' {
  declare module.exports: any;
}

declare module '@primer/components/src/Caret' {
  declare module.exports: any;
}

declare module '@primer/components/src/CircleBadge' {
  declare module.exports: any;
}

declare module '@primer/components/src/CircleOcticon' {
  declare module.exports: any;
}

declare module '@primer/components/src/constants' {
  declare module.exports: any;
}

declare module '@primer/components/src/CounterLabel' {
  declare module.exports: any;
}

declare module '@primer/components/src/css' {
  declare module.exports: any;
}

declare module '@primer/components/src/Details' {
  declare module.exports: any;
}

declare module '@primer/components/src/Donut' {
  declare module.exports: any;
}

declare module '@primer/components/src/Dropdown' {
  declare module.exports: any;
}

declare module '@primer/components/src/DropdownStyles' {
  declare module.exports: any;
}

declare module '@primer/components/src/FilterList' {
  declare module.exports: any;
}

declare module '@primer/components/src/Flash' {
  declare module.exports: any;
}

declare module '@primer/components/src/Flex' {
  declare module.exports: any;
}

declare module '@primer/components/src/Heading' {
  declare module.exports: any;
}

declare module '@primer/components/src/index' {
  declare module.exports: any;
}

declare module '@primer/components/src/Label' {
  declare module.exports: any;
}

declare module '@primer/components/src/Link' {
  declare module.exports: any;
}

declare module '@primer/components/src/PointerBox' {
  declare module.exports: any;
}

declare module '@primer/components/src/Position' {
  declare module.exports: any;
}

declare module '@primer/components/src/PrimerComponentsAnimation' {
  declare module.exports: any;
}

declare module '@primer/components/src/StateLabel' {
  declare module.exports: any;
}

declare module '@primer/components/src/StyledOcticon' {
  declare module.exports: any;
}

declare module '@primer/components/src/Text' {
  declare module.exports: any;
}

declare module '@primer/components/src/TextInput' {
  declare module.exports: any;
}

declare module '@primer/components/src/theme' {
  declare module.exports: any;
}

declare module '@primer/components/src/Tooltip' {
  declare module.exports: any;
}

declare module '@primer/components/src/UnderlineNav' {
  declare module.exports: any;
}

// Filename aliases
declare module '@primer/components/codemods/__tests__/v1.js' {
  declare module.exports: $Exports<'@primer/components/codemods/__tests__/v1'>;
}
declare module '@primer/components/codemods/__tests__/v2.js' {
  declare module.exports: $Exports<'@primer/components/codemods/__tests__/v2'>;
}
declare module '@primer/components/codemods/__tests__/v3.js' {
  declare module.exports: $Exports<'@primer/components/codemods/__tests__/v3'>;
}
declare module '@primer/components/codemods/__tests__/v4.js' {
  declare module.exports: $Exports<'@primer/components/codemods/__tests__/v4'>;
}
declare module '@primer/components/codemods/lib/modifyProps.js' {
  declare module.exports: $Exports<'@primer/components/codemods/lib/modifyProps'>;
}
declare module '@primer/components/codemods/lib/prettify.js' {
  declare module.exports: $Exports<'@primer/components/codemods/lib/prettify'>;
}
declare module '@primer/components/codemods/lib/renameImports.js' {
  declare module.exports: $Exports<'@primer/components/codemods/lib/renameImports'>;
}
declare module '@primer/components/codemods/lib/replaceImportSource.js' {
  declare module.exports: $Exports<'@primer/components/codemods/lib/replaceImportSource'>;
}
declare module '@primer/components/codemods/v1.js' {
  declare module.exports: $Exports<'@primer/components/codemods/v1'>;
}
declare module '@primer/components/codemods/v2.js' {
  declare module.exports: $Exports<'@primer/components/codemods/v2'>;
}
declare module '@primer/components/codemods/v3.js' {
  declare module.exports: $Exports<'@primer/components/codemods/v3'>;
}
declare module '@primer/components/codemods/v4.js' {
  declare module.exports: $Exports<'@primer/components/codemods/v4'>;
}
declare module '@primer/components/css.js' {
  declare module.exports: $Exports<'@primer/components/css'>;
}
declare module '@primer/components/dist/css.js' {
  declare module.exports: $Exports<'@primer/components/dist/css'>;
}
declare module '@primer/components/dist/index.esm.js' {
  declare module.exports: $Exports<'@primer/components/dist/index.esm'>;
}
declare module '@primer/components/dist/index.umd.js' {
  declare module.exports: $Exports<'@primer/components/dist/index.umd'>;
}
declare module '@primer/components/src/Avatar.js' {
  declare module.exports: $Exports<'@primer/components/src/Avatar'>;
}
declare module '@primer/components/src/AvatarPair.js' {
  declare module.exports: $Exports<'@primer/components/src/AvatarPair'>;
}
declare module '@primer/components/src/BaseStyles.js' {
  declare module.exports: $Exports<'@primer/components/src/BaseStyles'>;
}
declare module '@primer/components/src/BorderBox.js' {
  declare module.exports: $Exports<'@primer/components/src/BorderBox'>;
}
declare module '@primer/components/src/Box.js' {
  declare module.exports: $Exports<'@primer/components/src/Box'>;
}
declare module '@primer/components/src/BranchName.js' {
  declare module.exports: $Exports<'@primer/components/src/BranchName'>;
}
declare module '@primer/components/src/Button.js' {
  declare module.exports: $Exports<'@primer/components/src/Button'>;
}
declare module '@primer/components/src/ButtonDanger.js' {
  declare module.exports: $Exports<'@primer/components/src/ButtonDanger'>;
}
declare module '@primer/components/src/ButtonOutline.js' {
  declare module.exports: $Exports<'@primer/components/src/ButtonOutline'>;
}
declare module '@primer/components/src/ButtonPrimary.js' {
  declare module.exports: $Exports<'@primer/components/src/ButtonPrimary'>;
}
declare module '@primer/components/src/ButtonStyles.js' {
  declare module.exports: $Exports<'@primer/components/src/ButtonStyles'>;
}
declare module '@primer/components/src/Caret.js' {
  declare module.exports: $Exports<'@primer/components/src/Caret'>;
}
declare module '@primer/components/src/CircleBadge.js' {
  declare module.exports: $Exports<'@primer/components/src/CircleBadge'>;
}
declare module '@primer/components/src/CircleOcticon.js' {
  declare module.exports: $Exports<'@primer/components/src/CircleOcticon'>;
}
declare module '@primer/components/src/constants.js' {
  declare module.exports: $Exports<'@primer/components/src/constants'>;
}
declare module '@primer/components/src/CounterLabel.js' {
  declare module.exports: $Exports<'@primer/components/src/CounterLabel'>;
}
declare module '@primer/components/src/css.js' {
  declare module.exports: $Exports<'@primer/components/src/css'>;
}
declare module '@primer/components/src/Details.js' {
  declare module.exports: $Exports<'@primer/components/src/Details'>;
}
declare module '@primer/components/src/Donut.js' {
  declare module.exports: $Exports<'@primer/components/src/Donut'>;
}
declare module '@primer/components/src/Dropdown.js' {
  declare module.exports: $Exports<'@primer/components/src/Dropdown'>;
}
declare module '@primer/components/src/DropdownStyles.js' {
  declare module.exports: $Exports<'@primer/components/src/DropdownStyles'>;
}
declare module '@primer/components/src/FilterList.js' {
  declare module.exports: $Exports<'@primer/components/src/FilterList'>;
}
declare module '@primer/components/src/Flash.js' {
  declare module.exports: $Exports<'@primer/components/src/Flash'>;
}
declare module '@primer/components/src/Flex.js' {
  declare module.exports: $Exports<'@primer/components/src/Flex'>;
}
declare module '@primer/components/src/Heading.js' {
  declare module.exports: $Exports<'@primer/components/src/Heading'>;
}
declare module '@primer/components/src/index.js' {
  declare module.exports: $Exports<'@primer/components/src/index'>;
}
declare module '@primer/components/src/Label.js' {
  declare module.exports: $Exports<'@primer/components/src/Label'>;
}
declare module '@primer/components/src/Link.js' {
  declare module.exports: $Exports<'@primer/components/src/Link'>;
}
declare module '@primer/components/src/PointerBox.js' {
  declare module.exports: $Exports<'@primer/components/src/PointerBox'>;
}
declare module '@primer/components/src/Position.js' {
  declare module.exports: $Exports<'@primer/components/src/Position'>;
}
declare module '@primer/components/src/PrimerComponentsAnimation.js' {
  declare module.exports: $Exports<'@primer/components/src/PrimerComponentsAnimation'>;
}
declare module '@primer/components/src/StateLabel.js' {
  declare module.exports: $Exports<'@primer/components/src/StateLabel'>;
}
declare module '@primer/components/src/StyledOcticon.js' {
  declare module.exports: $Exports<'@primer/components/src/StyledOcticon'>;
}
declare module '@primer/components/src/Text.js' {
  declare module.exports: $Exports<'@primer/components/src/Text'>;
}
declare module '@primer/components/src/TextInput.js' {
  declare module.exports: $Exports<'@primer/components/src/TextInput'>;
}
declare module '@primer/components/src/theme.js' {
  declare module.exports: $Exports<'@primer/components/src/theme'>;
}
declare module '@primer/components/src/Tooltip.js' {
  declare module.exports: $Exports<'@primer/components/src/Tooltip'>;
}
declare module '@primer/components/src/UnderlineNav.js' {
  declare module.exports: $Exports<'@primer/components/src/UnderlineNav'>;
}
